Split from executor
crypto-pepe/firewall-api pull request #1
Opened 2022-05-16 13:56 UTC by hehegrrrhehegrr

2022-05-18 12:32 UTC, stuffy-idler requested changes

2022-05-18 12:32 UTC, stuffy-idler commented on src/telemetry/mod.rs
> +pub use self::config::Config;
Let's stick to a single code style and use it without `self`

2022-05-18 12:32 UTC, stuffy-idler commented on src/config.rs
> +        match env::var("CONFIG_PATH") {
`CONFIG_PATH` reading already implemented in `pepe_config::load` therefore it excess and can be dropped

2022-05-19 13:58 UTC, stuffy-idler requested changes

2022-05-20 07:52 UTC, stuffy-idler requested changes

2022-05-20 07:52 UTC, stuffy-idler commented on src/server/server.rs
> +        Err(e) => {
This error should be converted to `ErrorResponse`

2022-05-20 07:52 UTC, stuffy-idler commented on src/server/response.rs
> +    pub error: Option<String>,
I think it will be cleaner if `CheckBanResponse` will respond for success responses only. For error responses there is `ErrorResponse`.

2022-05-20 07:52 UTC, stuffy-idler commented on src/server/response.rs
> +enum BanStatus {
It can be rewritten as:
```rust
#[derive(Serialize)]
#[serde(rename_all = "lowercase")]
#[serde(tag = "status")]
enum BanStatus {
  Free,
  Banned(BannedBanStatus),
}

#[derive(Serialize)]
struct BannedBanStatus {
  ban_expires_at: i64,
}
```
It will be json-ed as according to service API spec

2022-05-24 13:09 UTC, stuffy-idler requested changes

2022-05-24 13:09 UTC, stuffy-idler commented on Cargo.toml
> +name = "firewall-executor"
`firewall-api`

2022-05-24 13:09 UTC, stuffy-idler commented on Cargo.toml
> +name = "firewall_executor"
`firewall_api` or just `lib`

2022-05-24 13:09 UTC, stuffy-idler commented on config.yaml
> +redis_query_timeout_secs: 2
Update please similarly to `firewall-executor`

2022-05-24 13:09 UTC, stuffy-idler commented on docs/api/check-ban/post.md
> +| `target` | `{ ip: string?, user-agent:string? }` | Yes      | Ban target |
Update please similarly to `firewall-executor` (`user_agent`)

2022-05-24 13:09 UTC, stuffy-idler commented on src/api/mod.rs
> +pub use self::config::Config;
Whether `self` is needed?

2022-05-24 13:09 UTC, stuffy-idler commented on src/api/routes/check.rs
> +                let expires_at = match std::time::SystemTime::now().duration_since(UNIX_EPOCH) {
It should be done according to Utc, not `SystemTime`. You can use crate `chrono` and its `DateTime<Utc>`

2022-05-24 13:09 UTC, stuffy-idler commented on src/api/server.rs
> +    pub fn new(cfg: &Config, bc: RedisBanChecker) -> Result<Server, io::Error> {
Whether concrete implementation of `BanChecker` can be replaced with the trait constraint?

2022-05-24 13:09 UTC, stuffy-idler commented on src/api/server.rs
> +        let bh = Data::from(Arc::new(bc));
It's not `bh`, but `bc`

2022-05-24 13:54 UTC, hehegrrrhehegrr commented on config.yaml
> +redis_query_timeout_secs: 2
\+

2022-05-24 13:55 UTC, hehegrrrhehegrr commented on docs/api/check-ban/post.md
> +| `target` | `{ ip: string?, user-agent:string? }` | Yes      | Ban target |
\+

2022-05-24 13:55 UTC, hehegrrrhehegrr commented on src/api/routes/check.rs
> +                let expires_at = match std::time::SystemTime::now().duration_since(UNIX_EPOCH) {
\+

2022-05-24 16:17 UTC, stuffy-idler commented on src/model.rs
> +        let mut vv: Vec<String> = Vec::new();
Replace it with appropriate implementation from `firewall-executor`

2022-05-24 16:35 UTC, stuffy-idler requested changes

2022-05-24 16:35 UTC, stuffy-idler commented on src/api/server.rs
> +    pub fn new(cfg: &Config, bc: Box<dyn BanChecker + Sync + Send>) -> Result<Server, io::Error> {
It's better to provide `impl` instead of `dyn` for the performance reasons.

2022-05-25 14:49 UTC, stuffy-idler requested changes

2022-05-25 14:49 UTC, stuffy-idler commented on src/main.rs
> +mod errors;
Let's rename it according to other modules names – `error`

2022-05-25 14:49 UTC, stuffy-idler commented on readme.md
> +| redis_query_timeout       | No       | Redis query timeout. Duration string                                                     |
Missing default value specification

2022-05-26 15:51 UTC, stuffy-idler commented on src/main.rs
> +        Duration::from_std(dur).expect("bad timeout"),
To use `timeout` you are transforming it to `std::time::Duration` under the hood, so let use `std::time::Duration` anywhere instead of `chrono::Duration`

2022-05-26 16:07 UTC, stuffy-idler approved these changes

2022-05-26 16:09 UTC, merged