Dry run and unban
crypto-pepe/firewall-api pull request #12
Opened 2022-05-31 13:11 UTC by hehegrrrhehegrr

Because #5 and #8 works simillar I done them in one PR

2022-05-31 16:18 UTC, stuffy-idler requested changes

2022-05-31 16:18 UTC, stuffy-idler commented on src/executor/client.rs
> +            if payload.is_some() {
Better to handle it as:
```rust
if let Some(payload) = payload {
  // do something with payload
}
```

2022-05-31 16:18 UTC, stuffy-idler commented on src/executor/client.rs
> +                    .body(
It can be done with `json` method of builder – it will serialise payload to json and set necessary header

2022-05-31 16:18 UTC, stuffy-idler commented on src/executor/config.rs
> +pub struct ExecutorInfo {
I guess `ExecutorConfig` will be better name for this structure

2022-06-01 09:37 UTC, hehegrrrhehegrr commented on docs/api/enable-dry-run/post.md
> +**URL** : `/api/enable-dry-run`
\+

2022-06-01 09:37 UTC, hehegrrrhehegrr commented on docs/api/enable-dry-run/post.md
> +**Method** : `POST`
\+

2022-06-01 09:37 UTC, hehegrrrhehegrr commented on docs/api/unban/post.md
> +**URL** : `/api/unban`
\+

2022-06-01 09:38 UTC, hehegrrrhehegrr commented on docs/api/unban/post.md
> +**Condition** : Ban was successfully applied.
\+

2022-06-01 09:38 UTC, hehegrrrhehegrr commented on src/executor/client.rs
> +            if payload.is_some() {
\+

2022-06-01 09:38 UTC, hehegrrrhehegrr commented on src/executor/client.rs
> +                    .body(
\+

2022-06-01 09:38 UTC, hehegrrrhehegrr commented on src/executor/config.rs
> +pub struct ExecutorInfo {
\+

2022-06-01 12:37 UTC, stuffy-idler requested changes

2022-06-01 12:37 UTC, stuffy-idler commented on src/executor/client.rs
> +                    .header(CONTENT_TYPE, "application/json".to_string());
It's excess, because of `json`-call make it under-the-hood

2022-06-01 12:37 UTC, stuffy-idler commented on src/executor/client.rs
> +        let mut ubs = Vec::new();
Name it more descriptive

2022-06-02 16:32 UTC, stuffy-idler requested changes

2022-06-02 16:32 UTC, stuffy-idler commented on src/main.rs
>      let ban_checker = match RedisBanChecker::new(
I suggest to rewrite it using question mark (alongside with cfg loading and redis pool initialising)

2022-06-06 08:57 UTC, merged