Add api key
crypto-pepe/firewall-api pull request #13
Opened 2022-06-07 14:11 UTC by horny-manul

2022-06-07 16:28 UTC, stuffy-idler requested changes

2022-06-07 16:28 UTC, stuffy-idler commented on src/api/routes/dry_run.rs
> +    api_key_checker.check(&req)?;
It should be done with actix `guard`

2022-06-07 16:28 UTC, stuffy-idler commented on readme.md
> +| api_key_header            | string                             | Yes      |         | Name of header with API-key                                                              |
`api_key_header` is overcomplication for this case.

2022-06-08 16:47 UTC, stuffy-idler approved these changes

2022-06-08 16:49 UTC, stuffy-idler commented
@citizensix please review this PR

2022-06-09 10:41 UTC, citizensix commented on src/api/auth.rs
> +        ApiKeyChecker { key }
Consider using `Self` or `ApiKeyChecker` in both cases

2022-06-09 10:41 UTC, citizensix commented on src/api/routes/unban.rs
>  pub struct UnBanRequest {
`UnBan` looks weird -> `Unban`

2022-06-09 10:41 UTC, citizensix commented on src/api/server.rs
>          let bc = Data::from(Arc::new(bc));
Consider renaming `bc` to `ban_checker`

2022-06-09 10:41 UTC, citizensix commented on src/api/server.rs
>          let ec = Data::from(Arc::new(executor_client));
My first thought on`bc` `ec` and `kc` was that they are some kind of `-checker` but it looks like that they're not. So there I suggest using `executor_client_data` instead of `ec` so it won't mix with `checkers`

2022-06-10 09:57 UTC, citizensix approved these changes
LGTM

2022-06-10 10:06 UTC, stuffy-idler commented
@horny-manul it can be merged

2022-06-14 08:01 UTC, merged