Add API for unban
crypto-pepe/firewall-api pull request #8
Opened 2022-05-27 11:17 UTC by hehegrrrhehegrr

2022-05-30 09:13 UTC, stuffy-idler requested changes

2022-05-30 09:13 UTC, stuffy-idler commented on src/unban/service.rs
> +        for exec in &self.executors {
I suggest to rename `exec` to `executor` – `exec` is commonly used name for function, and saving 4 symbols in the variable name will worsen readability

2022-05-30 09:13 UTC, stuffy-idler commented on src/unban/service.rs
> +        for exec in &self.executors {
It's better to rewrite `for - in` to combination of `map` that will produce vec of futures and `futures::future::join_all` that will executor all of them concurrently and return ordered vec of outputs

2022-05-30 09:13 UTC, stuffy-idler commented on src/model.rs
> +        f.write_str(serde_json::to_string(self).unwrap().as_str())
`unwrap` usage is dangerous for runtime. Moreover, inside a function that returns `Result` it should be replaced with `Err`

2022-05-30 09:13 UTC, stuffy-idler commented on src/main.rs
>      let dur: std::time::Duration = cfg.redis_query_timeout.into();
`dur` is not descriptive name, change it

2022-05-30 09:13 UTC, stuffy-idler commented on src/main.rs
> +mod unban;
I suggest to name it similarly to `ban_checker`, e.g. `unbanner`

2022-06-06 17:10 UTC, stuffy-idler requested changes

2022-06-06 17:10 UTC, stuffy-idler commented on src/error.rs
> +    IPOrUserAgentRequired,
It's not extendable error name, I suggest to name it `MissingField` or something similar

2022-06-06 17:10 UTC, stuffy-idler commented on src/api/routes/unban.rs
> +            let err_resp: ErrorResponse = e.into();
I guess it can be done without extra variable

2022-06-08 08:09 UTC, closed without merging

2022-06-08 08:23 UTC, horny-manul commented on src/unban/service.rs
> +                .body(serde_json::to_vec(&ur).expect("UnBanEntity derives Serialize"))
done here https://github.com/crypto-pepe/firewall-api/pull/12/files#diff-2fc5713c1adda4e554a333bc88f0c0781d144c34ea47d86c3f9209123e2bfd79R56

2022-06-08 08:24 UTC, horny-manul commented on src/api/routes/unban.rs
> +        if self.target.is_none() {
done here https://github.com/crypto-pepe/firewall-api/pull/12/files#diff-c1591b764f87289591af441242f855ede3b0b57d71267f9a2beece30697c11d1R17

2022-06-08 08:26 UTC, horny-manul commented on src/api/routes/unban.rs
> +            let err_resp: ErrorResponse = e.into();
done here https://github.com/crypto-pepe/firewall-api/pull/13/files#diff-a4487fc58e096dc35553836b2e679c57256578af38b1e97e2ae83ece311e0652R27